//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorDeploymentAgent {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp")]
        public string DropPath {
            get {
                return ((string)(this["DropPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("manager")]
        public string EpicorUser {
            get {
                return ((string)(this["EpicorUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("manager")]
        public string EpicorPassword {
            get {
                return ((string)(this["EpicorPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C001")]
        public string EpicorCompany {
            get {
                return ((string)(this["EpicorCompany"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\epicor\ERP10.2Client\SG_Production\Client\config\EpicorLive10_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Production\Client\config\EpicorPilot10_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Production\Client\config\EpicorTest10_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Production\Client\config\EpicorTrain10_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Development\Client\config\EpicorA_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Development\Client\config\EpicorB_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Development\Client\config\EpicorC_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Development\Client\config\EpicorD_SSL.sysconfig</string>
  <string>C:\epicor\ERP10.2Client\SG_Development\Client\config\EpicorE_SSL.sysconfig</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EpicorSysConfigs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EpicorSysConfigs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\epicor\\ERP10.2Client\\SG_Production\\Client\\Solution.exe")]
        public string EpicorSolutionPath {
            get {
                return ((string)(this["EpicorSolutionPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public string LogLevel {
            get {
                return ((string)(this["LogLevel"]));
            }
        }
    }
}
